### ISSUE TITLE
Null-safety

### ISSUE THREAD

**Issue by anaurelian** [DAMMAK/RandomColorDart#2]
I get this warning when trying to import `package:flutter_randomcolor/flutter_randomcolor.dart`:

> The library 'package:flutter_randomcolor/flutter_randomcolor.dart' is legacy, and should not be imported into a null safe library.  Try migrating the imported library.

Do you have any plans to migrate this package to null-safety?

**Comment by anaurelian** [comment]
That's great! Thanks

**Comment by DAMMAK** [comment]
Migrated to null-safety
