### ISSUE TITLE
_CastError (Null check operator used on a null value)

### ISSUE THREAD

**Issue by LennartMart** [DAMMAK/RandomColorDart#4]
When getting a Random Color, a casterror occurs.
Steps to reproduce:
` var options = Options(format: Format.hex, colorType: ColorType.random);
var color = RandomColor.getColor(options);
`
Culprit:
`  static void __loadColorBounds() {
    _defineColor(
      colorType: ColorType.monochrome,
      hueRange: null,
      lowerBounds: [
        [0, 0],
        [100, 0],
      ],
    );
`

hueRange is null, but it's used in Range.toRange, which expects a non-null value.

My Flutter version:
`flutter --version
Flutter 3.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 85684f9300 (3 weeks ago) • 2022-06-30 13:22:47 -0700
Engine • revision 6ba2af10bb
Tools • Dart 2.17.5 • DevTools 2.12.2`

**Comment by DAMMAK** [comment]
okay.. Thanks for this, I will try to recreate the issue and fix it
