### ISSUE TITLE
Can you add a seed parameter to options?

### ISSUE THREAD

**Issue by huangred** [DAMMAK/RandomColorDart#6]
We can get a color by the hash value of parameter

**Comment by DAMMAK** [comment]
hash value? you mean hex ?

**Comment by nicolasbraun** [comment]
@DAMMAK 

I think what he meant is to be able to pass an hash/seed in the option to be able to always retrieve the same color (for the same other options).

My usecase is I want to create a color for each userId I have and I want it to remain the same
