### ISSUE TITLE
Please avoid print statement in package code

### ISSUE THREAD

**Issue by khaven** [DAMMAK/RandomColorDart#7]
Can you please remove all print statement from package code? 
It's annoying to see all these print statement like this one:

`Hex component => 142`

**Comment by TechAurelian2** [comment]
This seems to be the source of the problem:

https://github.com/DAMMAK/RandomColorDart/blob/main/lib/src/randomcolor.dart#L270

```dart
static _componentToHex(int c) {
    print("Hex component => $c");
    var hex = c.toRadixString(16);
    return hex.length == 1 ? '0' + hex : hex;
  }
```

Can you please remove it and release a new build? Thank you
