### ISSUE TITLE
Convert RandomColor.getColor() to Color class

### ISSUE THREAD

**Issue by calvinzhe** [DAMMAK/RandomColorDart#9]
I am having issues converting RandomColor.getColor(), which is of type string formatted depending on the options, to a Color class.

The Color() object can covert a hex data type to color, but not a string formatted as a hex, so roundabout solution is to write a new function to automatically do this (https://stackoverflow.com/questions/49835146/how-to-convert-flutter-color-to-string-and-back-to-a-color) or use another package (like https://pub.dev/documentation/string_to_hex/latest/).

It would be nice if the RandomColor package can already do this built-in.

**Comment by DAMMAK** [comment]
okay. I will see to it

**Comment by DAMMAK** [comment]
@calvinzhe , I have pushed a new version that addressed this issue, kindly check the doc concerning this. Thank you for the feedback. if there is any other issue kindly help create the issue for it.

I will close this issue now
